In [ ]:
#Problem1
#Task1
import numpy as np
array=np.empty((2,2))
print(array)

[[0. 0.]
 [0. 0.]]


In [ ]:
#Task2
import numpy as np
array=np.ones((4,2))
print(array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#Task3
import numpy as np
shape=(3,3)
fill_value=3
dtype=int
array=np.full(shape,fill_value,dtype=dtype)
print(array)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [ ]:
#Task4
import numpy as np
array=np.array(([1,2,3],[3,2,1]))
zeros_array=np.zeros_like(array)
print("Array:")
print(array)
print("\nNew array:")
print(zeros_array)

Array:
[[1 2 3]
 [3 2 1]]

New array:
[[0 0 0]
 [0 0 0]]


In [ ]:
#Task5
import numpy as np
array=np.array(([1,2,3],[3,2,1]))
ones_array=np.ones_like(array)
print("Array:")
print(array)
print("\nNew array:")
print(ones_array)

Array:
[[1 2 3]
 [3 2 1]]

New array:
[[1 1 1]
 [1 1 1]]


In [ ]:
#Task6
import numpy as np
new_list=[1,2,3,4]
new_array=np.array(new_list)
print(new_array)

[1 2 3 4]


In [ ]:
#Problem2
#Task1
import numpy as np
array=np.arange(10,50)
print("Array ranging from 10 to 49:")
print(array)

Array ranging from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#Task2
import numpy as np
array=np.arange(9)
matrix=array.reshape(3,3)
print("Matrix ranging from 0 to 8:")
print(matrix)

Matrix ranging from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Task3
import numpy as np
array=np.eye(3,3)
print("Identity matrix:")
print(array)

Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Task4
import numpy as np
random_array=np.random.random(30)
mean_value=random_array.mean()
print("Random array:",random_array)
print("\nMean:",mean_value)

Random array: [0.09809595 0.58354256 0.58315088 0.09839974 0.87761925 0.38886024
 0.81371235 0.94726437 0.34627173 0.46966659 0.00246106 0.73695025
 0.54597743 0.73245802 0.54966428 0.18844657 0.60432061 0.13947532
 0.71575514 0.31083771 0.31199978 0.75347448 0.30596997 0.11076985
 0.30225681 0.47480039 0.4345879  0.64932083 0.35050581 0.96527783]

Mean: 0.47972978973350944


In [ ]:
#Task5
import numpy as np
ran_array=np.random.random((10,10))
min_value=ran_array.min()
max_value=ran_array.max()
print("Random array:",ran_array)
print("Minimum value:",min_value)
print("Maximum value:",max_value)

Random array: [[0.98683076 0.57310018 0.71240647 0.58621914 0.02770495 0.44980117
  0.34352643 0.40921351 0.11947299 0.38095651]
 [0.03766465 0.64291715 0.18357123 0.55095526 0.94617434 0.41052885
  0.59586248 0.18387478 0.30293051 0.65678453]
 [0.34626071 0.94887703 0.80434427 0.74985152 0.1244556  0.00450202
  0.7414926  0.24758145 0.14542919 0.17102887]
 [0.14266281 0.19622345 0.56461925 0.35551461 0.12918122 0.51914669
  0.16155578 0.13540665 0.7194373  0.77941589]
 [0.94131304 0.72084965 0.75077435 0.45047786 0.720823   0.06554876
  0.96029521 0.72836137 0.93322739 0.75964851]
 [0.67850572 0.43360745 0.80815858 0.14168251 0.04010621 0.00408521
  0.54874877 0.13819673 0.94930686 0.23644846]
 [0.89320704 0.7027019  0.71625359 0.14423756 0.25519457 0.43948438
  0.52107499 0.76856219 0.14109886 0.99334401]
 [0.05449414 0.38235097 0.11615869 0.02381557 0.6796221  0.50861982
  0.57486151 0.46776465 0.50804845 0.06589568]
 [0.49020147 0.03951266 0.85655157 0.54379404 0.84042394 0.6614119

In [ ]:
#Task6
import numpy as np
array = np.zeros(10)
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#Task7
import numpy as np
arr=np.array([1,2,0,0,4,0])
print("Array:",arr)
reverse_array=np.flip(arr)
print("Reverse array:",reverse_array)

Array: [1 2 0 0 4 0]
Reverse array: [0 4 0 0 2 1]


In [ ]:
#Task8
import numpy as np
n=5
arr=np.ones((n,n),dtype=int)
arr[1:-1,1:-1]=0
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
#Task9
import numpy as np
n=8
arr=np.zeros((n,n),dtype=int)
arr[::2,::2]=1
arr[1::2,1::2]=1
print(arr)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [ ]:
#Problem 3
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print("Add:\n", np.add(x, y)) # Output Add: [5 7 9]
print("Subtract:", np.subtract(v, w))
print("Multiply:\n", np.multiply(x, y))
print("Square:", np.power(v, 2))
v_w = np.dot(v, w)
print("Result v_w:\n", v_w)
x_y = np.dot(x, y)
print("Result x_y:\n", x_y)
x_v = np.dot(x, v)
print("Result x_v:\n", x_v)
concat_row= np.concatenate((x, y), axis=0)
print("Concatenation of x and y along rows:")
print(concat_row)
concat_vw_col = np.vstack((v, w))
print("\nConcatenation of v and w along columns:")
print(concat_vw_col)
#Task7
#This comes about in an blunder since x could be a 2-dimensional array,
#whereas v may be a 1-dimensional array.
#The error message: all the input arrays must have same number of dimensions,
#but the array at record has 2 dimensions and the array at index 1 has 1 dimension.

Add:
 [[ 6  8]
 [10 13]]
Subtract: [-2 -2]
Multiply:
 [[ 5 12]
 [21 40]]
Square: [ 81 100]
Result v_w:
 219
Result x_y:
 [[19 22]
 [50 58]]
Result x_v:
 [29 77]
Concatenation of x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
[[ 9 10]
 [11 12]]


In [ ]:
#Problem 4 (1)
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
#1. Prove A.A−1 = I
a_inv=np.linalg.inv(A)
I=np.identity(2)
result=np.dot(A,a_inv)
result = np.round(result).astype(int)
print("A * A^-1 = \n", result)
print("Is A * A^-1 equal to the identity matrix? ", np.allclose(result, I))
#2. Prove AB ̸= BA.
a = np.dot(A, B)
b= np.dot(B, A)
print("\nAB = \n", a)
print("BA = \n", b)
print("Is AB equal to BA? ", np.array_equal(a, b))
#3. Prove (AB)T = BTAT
abt=np.transpose(a)
bt_at=np.dot(np.transpose(B),np.transpose(A))
print("(AB)T=\n",abt)
print("(AT*BT=\n",bt_at)
print("Is (AB)T equal to BT*AT? ", np.array_equal(abt,bt_at))


A * A^-1 = 
 [[1 0]
 [0 1]]
Is A * A^-1 equal to the identity matrix?  True

AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]
Is AB equal to BA?  False
(AB)T=
 [[23 51]
 [13 29]]
(AT*BT=
 [[23 51]
 [13 29]]
Is (AB)T equal to BT*AT?  True


In [ ]:
#Problem 4 (2)
#Solve the following system of Linear equation using Inverse Methods.
#2x − 3y + z = −1
#x − y + 2z = −3
#3x + y − z = 9
import numpy as np
A=np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B=np.array([-1,-3,9])
A_inverse=np.linalg.inv(A)
X=np.dot(A_inverse,B)
print(f"The value of x ,y and z is {X[0]} {X[1]} {X[2]} respectively")
#Now: solve the above equation using np.linalg.inv function.
print("\nFrom using np.linalg.inv function\n")
X_solve=np.linalg.solve(A,B)
x_solve=np.round(X_solve).astype(int)
print(f"x={x_solve[0]} y={x_solve[1]} and z={x_solve[2]}")

The value of x ,y and z is 2.0 1.0 -2.0 respectively

From using np.linalg.inv function

x=2 y=1 and z=-2
